# OSSF Scorecard workflow.
# Author: Admilson B. F. Cossa
# SPDX-License-Identifier: Apache-2.0

name: OSSF Scorecard

on:
  workflow_dispatch:
  schedule:
    - cron: "19 3 * * 1"

permissions:
  contents: read

jobs:
  scorecard:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write
    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
